# Railway + Vanna migration, Phase 7 (see .claude/skills/railway-vanna-migration/SKILL.md).
# /generate-sql now calls the real, trained Vanna object (app/vanna_client.py) — no more
# hardcoded stub. Built against `vanna.legacy` (see the Phase 7 entry for the researched
# reasoning over vanna.core/vanna.agents).
#
# Permanent implementation note (kept from Phase 5, still load-bearing): this endpoint calls
# only a SQL-*generation*-only method (`generate_sql(question, allow_llm_to_see_data=False)`)
# — never `ask()`, and this service never mounts Vanna's own built-in web app
# (`VannaFlaskApp`). Both execute SQL against a live database by default — they're built for
# Vanna's own end-user chat UI, not a generation-only backend API — so using either naively
# would silently violate the "Vanna never executes" guardrail.
# `allow_llm_to_see_data` is hardcoded False, never a request field: passing True lets
# generate_sql() internally call run_sql() on intermediate queries — NucaseVanna has no SQL
# *runner* mixin at all (only OpenAI_Chat + PG_VectorStore), so that path would fail loudly
# rather than silently reach a database if this were ever changed by mistake, but it must
# never be set True regardless.
#
# This endpoint never receives or forwards a company/tenant identifier (decision 4) —
# GenerateSqlRequest below has no such field, by design, not oversight. Connection routing
# happens entirely in the Node backend (server/src/tenant/connectionResolver.ts); Vanna only
# ever sees a natural-language question and the shared, curated schema context it was trained
# on (server/db/generateVannaTrainingData.ts).
from __future__ import annotations

from dotenv import load_dotenv

# Loads vanna-service/.env into the process environment. Nothing previously did this for the
# actual running app (only individual test files loaded it ad hoc) — harmless while
# /generate-sql was a stub that touched no env vars, but a real gap now that it calls
# get_vanna_client(), which needs OPENROUTER_API_KEY/VANNA_DATABASE_URL at request time. Must
# run before any request is handled; doesn't need to run before the imports below since both
# read env vars lazily (get_vanna_client()'s cache is built on first call, not at import time).
load_dotenv()

from fastapi import FastAPI, HTTPException  # noqa: E402
from pydantic import BaseModel  # noqa: E402

from .vanna_client import get_vanna_client  # noqa: E402

app = FastAPI(title="Nucase Vanna Service")


class GenerateSqlRequest(BaseModel):
    question: str


class GenerateSqlResponse(BaseModel):
    sql: str
    stub: bool
    note: str


@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}


@app.post("/generate-sql", response_model=GenerateSqlResponse)
async def generate_sql(request: GenerateSqlRequest) -> GenerateSqlResponse:
    try:
        vn = get_vanna_client()
        sql = vn.generate_sql(request.question, allow_llm_to_see_data=False)
    except Exception as exc:  # noqa: BLE001 — surface as a clean 502, not a stack trace
        raise HTTPException(
            status_code=502, detail=f"SQL generation failed: {exc}"
        ) from exc

    return GenerateSqlResponse(
        sql=sql,
        stub=False,
        note="Generated by vanna.legacy against the curated training schema.",
    )


if __name__ == "__main__":
    # Railway + Vanna migration, Phase 9. Reads $PORT from the process environment directly in
    # Python rather than relying on shell expansion of a `--port $PORT`-style CLI string — found
    # empirically that Railway's stored `startCommand` is not reliably run through a shell (a
    # literal, unexpanded "$PORT" reached uvicorn's CLI parser across several deploy attempts,
    # regardless of quoting/wrapping tried). os.environ works correctly regardless of how this
    # process was launched, sidestepping that platform quirk entirely. Container entrypoint is
    # `python -m app.main` (see Dockerfile) — not used for local dev, which still runs
    # `uvicorn app.main:app --reload` directly per the README.
    import os

    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("PORT", 8000)))
