# Railway + Vanna migration, Phase 7 (see .claude/skills/railway-vanna-migration/SKILL.md).
# Trains NucaseVanna on the curated, allowlist-scoped DDL + bilingual (EN/PT) example
# question/SQL pairs generated by server/db/generateVannaTrainingData.ts (run that first,
# writing vanna-service/training_data.json, before running this).
#
# Idempotent: `vanna.legacy`'s train() has no built-in dedup (every call inserts a fresh
# UUID-keyed row — confirmed by reading vanna/legacy/pgvector/pgvector.py directly), so this
# script clears its own previously-trained rows first via get_training_data() +
# remove_training_data(id), then re-inserts everything from training_data.json fresh. Safe to
# re-run any time the curated training data changes.
#
# Usage (from vanna-service/, with VANNA_DATABASE_URL pointed at wherever the vanna schema
# actually lives — e.g. the Railway tunnel — and a fresh vanna_app password, never a reused
# or persisted one):
#   .venv/Scripts/python train.py
from __future__ import annotations

import json
import os
import sys

from dotenv import load_dotenv

load_dotenv()

from app.vanna_client import build_vanna_client  # noqa: E402


def main() -> None:
    data_path = os.path.join(os.path.dirname(__file__), "training_data.json")
    with open(data_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    vn = build_vanna_client()

    existing = vn.get_training_data()
    if not existing.empty:
        print(f"Clearing {len(existing)} previously-trained row(s)...")
        for row_id in existing["id"]:
            vn.remove_training_data(id=row_id)
        print("Cleared.")

    ddl_count = 0
    for tab_key, ddl in data["ddlByTab"].items():
        vn.train(ddl=ddl)
        print(f"Trained DDL for '{tab_key}'")
        ddl_count += 1

    pair_count = 0
    for pair in data["examplePairs"]:
        vn.train(question=pair["question_en"], sql=pair["sql"])
        vn.train(question=pair["question_pt"], sql=pair["sql"])
        print(f"Trained question/SQL pair (EN+PT) for tab '{pair['tab']}'")
        pair_count += 1

    print(
        f"\nDone. Trained {ddl_count} DDL statement(s) and {pair_count} bilingual "
        f"question/SQL pair(s) ({pair_count * 2} rows total)."
    )

    verify = vn.get_training_data()
    print(f"get_training_data() now reports {len(verify)} row(s) total.")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # noqa: BLE001 — top-level script, want a clean message + nonzero exit
        print(f"Training failed: {exc}", file=sys.stderr)
        sys.exit(1)
